<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">

<title></title>

<!-- Bootstrap core CSS -->
<link href="${pageContext.request.contextPath}/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom styles for this template -->
<link href="${pageContext.request.contextPath}/css/style.css"
	rel="stylesheet">
<link href="${pageContext.request.contextPath}/css/carousel.css"
	rel="stylesheet">

<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
	window.jQuery
			|| document
					.write('<script src="'${pageContext.request.contextPath}'/js/jquery.min.js"><\/script>')
</script>
<script src="${pageContext.request.contextPath}/js/bootstrap.min.js"></script>
<script
	src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container marketing">
		<form:form cssClass="form" method="POST" action="updateDoctor.html"
			modelAttribute="doctor">
			<h2 class="" style="text-align: center;">Update Doctor</h2>
			<div class="form-group row">
				<form:label path="doctorId" for="id"
					cssClass="col-sm-3 col-form-label">Doctor ID</form:label>
				<div class="col-sm-9">
					<form:input path="doctorId" cssClass="form-control"
						placeholder="Doctor ID will be autogenerated" readonly="true" />
					<span class="form-control-feedback"></span>
				</div>
			</div>
			<div class="form-group row">
				<form:label path="doctorName" for="fullName"
					cssClass="col-sm-3 col-form-label">Doctor Name</form:label>
				<div class="col-sm-9">
					<form:input path="doctorName" cssClass="form-control"
						placeholder="Doctor Name" />
					<span class="form-control-feedback"></span>
				</div>
			</div>
			<div class="form-group row">
				<form:label path="isAdmin" class="col-sm-3"
					for="inlineFormCustomSelect">Admin?</form:label>
				<div class="col-sm-9">
					<form:select path="isAdmin" class="form-control "
						id="inlineFormCustomSelect" name="departmentId">
						<!-- <option selected></option> -->
						<option value="Yes">Yes</option>
						<option value="No">No</option>
					</form:select>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-3" for="inlineFormCustomSelect">Department</label>
				<div class="col-sm-9">
					<select class="form-control " name="departmentId">
						<c:forEach items="${deparmentList}" var="department">
							<option value="${department.departmentId}">${department.departmentName}</option>
						</c:forEach>
					</select>
				</div>
			</div>
			<div class="form-group row">
				<form:label path="email" for="email" class="col-sm-3 col-form-label">Email</form:label>
				<div class="col-sm-9">
					<form:input path="email" class="form-control" placeholder="Email" />
					<span class="form-control-feedback"></span>
				</div>
			</div>
			<div class="form-group row">
				<form:label path="password" class="col-sm-3 col-form-label">Password</form:label>
				<div class="col-sm-9">
					<form:input path="password" type="password" class="form-control"
						id="password1" name="password1" />
				</div>
			</div>
			<div class="text-center">
				<input class="btn btn-primary" type="submit" value="Update Doctor" />
			</div>
		</form:form>
	</div>
</body>
</html>